#ifndef GAME_SERVER_AI_INVASION_PROFILE_H
#define GAME_SERVER_AI_INVASION_PROFILE_H

#include <game/weapons/weapon_catalog.h>

enum EInvasionSkinId
{
	INVASION_SKIN_ALIEN1,
	INVASION_SKIN_ALIEN2,
	INVASION_SKIN_ALIEN3,
	INVASION_SKIN_ALIEN4,
	INVASION_SKIN_ALIEN5,
	INVASION_SKIN_BUNNY1,
	INVASION_SKIN_BUNNY2,
	INVASION_SKIN_BUNNY3,
	INVASION_SKIN_FOXY1,
	INVASION_SKIN_BUNNY4,
	INVASION_SKIN_ROBO1,
	INVASION_SKIN_ROBO2,
	INVASION_SKIN_ROBO3,
	INVASION_SKIN_ROBO4,
	INVASION_SKIN_ROBO5,
	INVASION_SKIN_PYRO1,
	INVASION_SKIN_PYRO2,
	INVASION_SKIN_SKELETON1,
	INVASION_SKIN_SKELETON2,
	INVASION_SKIN_SKELETON3,
	INVASION_SKIN_PYRO3,

	INVASION_SKIN_CYBORG_GUNNER,
	INVASION_SKIN_CYBORG_RAIL,
	INVASION_SKIN_CYBORG_BREACHER,

	INVASION_SKIN_ELITE_ALIEN_ALPHA,
	INVASION_SKIN_ELITE_ALIEN_BIO,
	INVASION_SKIN_ELITE_ALIEN_STALKER,
	INVASION_SKIN_ELITE_ROBOT_COMMANDER,
	INVASION_SKIN_ELITE_ROBOT_RAIL,
	INVASION_SKIN_ELITE_ROBOT_BREACHER,
	INVASION_SKIN_ELITE_PYRO_SIEGE,
	INVASION_SKIN_ELITE_PYRO_BOUNCER,
	INVASION_SKIN_ELITE_PYRO_FURNACE,
	INVASION_SKIN_ELITE_BUNNY_ASSASSIN,
	INVASION_SKIN_ELITE_BUNNY_DUELIST,
	INVASION_SKIN_ELITE_BUNNY_SABOTEUR,

	NUM_INVASION_SKINS,
	INVASION_SKIN_INVALID = -1,
};

enum EInvasionFamily
{
	INVASION_FAMILY_ALIEN,
	INVASION_FAMILY_ROBOT,
	INVASION_FAMILY_PYRO,
	INVASION_FAMILY_BUNNY,
	INVASION_FAMILY_CYBORG,
};

enum EInvasionMovementStrategy
{
	INVASION_MOVE_HOLD_RANGE,
	INVASION_MOVE_RUSH,
	INVASION_MOVE_KITE,
	INVASION_MOVE_STRAFE,
	INVASION_MOVE_FLANK,
	INVASION_MOVE_SIEGE,
	INVASION_MOVE_AMBUSH,
};

enum EInvasionTargetStrategy
{
	INVASION_TARGET_NEAREST,
	INVASION_TARGET_LOW_HEALTH,
	INVASION_TARGET_CLUSTER,
	INVASION_TARGET_ISOLATED,
	INVASION_TARGET_OBJECTIVE,
};

constexpr int INVASION_PROFILE_MAX_PRIMARY_CHOICES = 4;
constexpr int INVASION_PROFILE_MAX_UTILITY_WEAPONS = 3;

struct CInvasionSkinProfile
{
	EInvasionSkinId m_Id = INVASION_SKIN_INVALID;
	EInvasionFamily m_Family = INVASION_FAMILY_ALIEN;
	EInvasionMovementStrategy m_Movement = INVASION_MOVE_HOLD_RANGE;
	EInvasionTargetStrategy m_Targeting = INVASION_TARGET_NEAREST;

	CWeaponSpec m_aPrimaryChoices[INVASION_PROFILE_MAX_PRIMARY_CHOICES];
	int m_PrimaryCount = 0;
	CWeaponSpec m_aUtilityWeapons[INVASION_PROFILE_MAX_UTILITY_WEAPONS];
	int m_UtilityCount = 0;

	int m_PreferredRange = 500;
	int m_RetreatRange = 180;
	int m_ReactionTime = 2;
	int m_BurstTicks = 0;
	int m_RepositionTicks = 90;

	int m_Health = 60;
	int m_HealthPerLevel = 3;
	int m_HealthCap = 300;
	int m_Armor = 0;
	int m_ArmorPerLevel = 3;
	int m_ArmorCap = 300;
	int m_PowerLevel = 8;
	int m_TriggerLevel = 10;
	int m_ShockTicks = 0;

	bool m_AttackOnDamage = false;
	bool m_StartTriggered = false;
};

const CInvasionSkinProfile &InvasionSkinProfile(EInvasionSkinId Id);
bool IsValidInvasionSkinProfile(EInvasionSkinId Id);
EInvasionSkinId InvasionSkinForWave(int WaveType, int Level, bool Elite);

#endif
