#ifndef ENGINE_PLATFORM_EVENTS_H
#define ENGINE_PLATFORM_EVENTS_H

enum EPlatformServerEvent
{
	PLATFORM_EVENT_FIRST_INVASION,
	PLATFORM_EVENT_FIRST_HORDE,
	PLATFORM_EVENT_FIRST_EXTRACTION,
	PLATFORM_EVENT_INVASION_10,
	PLATFORM_EVENT_INVASION_30,
	PLATFORM_EVENT_INVASION_60,
	PLATFORM_EVENT_FIRST_FORGE,
	PLATFORM_EVENT_FIRST_BUILD,
	PLATFORM_EVENT_COOP_RESCUE,
	PLATFORM_EVENT_FIRST_PVP_WIN,
	PLATFORM_EVENT_FIRST_COOP_COMPLETE,
	PLATFORM_EVENT_FIRST_BOSS,
	PLATFORM_EVENT_LB_INVASION_FLOOR,
	PLATFORM_EVENT_LB_FIXED_SEED_TIME_MS,
	PLATFORM_EVENT_STAT_COOP_COMPLETIONS,
	NUM_PLATFORM_SERVER_EVENTS,
};

inline bool PlatformEventIsLeaderboard(int Event)
{
	return Event == PLATFORM_EVENT_LB_INVASION_FLOOR || Event == PLATFORM_EVENT_LB_FIXED_SEED_TIME_MS;
}

inline bool PlatformEventIsStat(int Event)
{
	return Event == PLATFORM_EVENT_STAT_COOP_COMPLETIONS;
}

#endif
