STATIC_NAMES = (
	"TOOL", "GUN1", "GUN2", "GRENADE1", "GRENADE2", "GRENADE3", "BAZOOKA", "BOUNCER", "CHAINSAW",
	"FLAMER", "UPGRADE", "SHIELD", "RESPAWNER", "MASK1", "MASK2", "MASK3", "MASK4", "MASK5", "INVIS",
	"ELECTROWALL", "AREASHIELD", "SYRINGE", "CLUSTER", "SHURIKEN", "CLAW", "BOMB", "BALL",
)

RANGED_PART1_NAMES = ("BASE1", "BASE2", "BASE3", "BASE4")
RANGED_PART2_NAMES = ("BARREL1", "BARREL2", "BARREL3", "BARREL4", "CHARGE")
MELEE_PART1_NAMES = ("MELEE", "SPIN")
MELEE_PART2_NAMES = ("MELEE1", "MELEE2", "MELEE3", "MELEE4")

PART1_NAMES = RANGED_PART1_NAMES + MELEE_PART1_NAMES
PART2_NAMES = RANGED_PART2_NAMES + MELEE_PART2_NAMES

MODULAR_DEFINITION_FIRST = 100
DEFINITION_ID_MAX = MODULAR_DEFINITION_FIRST + len(PART1_NAMES) * len(PART2_NAMES) - 1
LEVEL_MAX = 15

VALID_MODULAR_COMBINATIONS = (
	(tuple((part1, part2) for part1 in RANGED_PART1_NAMES for part2 in RANGED_PART2_NAMES)) +
	tuple((part1, part2) for part1 in MELEE_PART1_NAMES for part2 in MELEE_PART2_NAMES)
)

DEFINITION_COUNT = len(STATIC_NAMES) + len(VALID_MODULAR_COMBINATIONS)
