#!/usr/bin/env bash
# Cross-compile Ninslash for Windows (x86_64) from Linux using MinGW-w64 + CMake.
#
# Typical deps (Debian/Ubuntu):
#   sudo apt-get install cmake ninja-build mingw-w64 g++-mingw-w64 python3 zlib1g-dev
#
# The client (-DCLIENT=ON) additionally needs SDL3 / Freetype / GLEW that CMake can find
# for the MinGW toolchain (often Mingw libs from distro or your own SYSROOT prefix).
# If configure fails on missing libs, try:
#   ./scripts/cross_build_windows.sh --server-only
#
# NOTICE: This script is generated by AI
set -eu

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

MINGW_TRIPLE="${MINGW_TRIPLE:-x86_64-w64-mingw32}"

BUILD_DIR="${PROJECT_ROOT}/build-windows-mingw"
BUILD_TYPE="${BUILD_TYPE:-Release}"
JOBS="$(nproc 2>/dev/null || echo 4)"
GENERATOR="${CMAKE_GENERATOR:-}"
SERVER_ONLY=0
FRESH=0
CUSTOM_SYSROOT=""
EXTRA_CMAKE=()

die() {
	echo >&2 "$*"
	exit 1
}

usage() {
	sed -n '1,/^set -eu$/p' "$0" >&2 || true
	cat >&2 <<'EOF'

Usage:
  scripts/cross_build_windows.sh [options] [-- passes-through-to-cmake ...]

Options:
  -h, --help          Show this help
  --build-dir PATH    CMake build dir (default: build-windows-mingw under repo root)
  --release|--debug   Set CMAKE_BUILD_TYPE (default: Release from BUILD_TYPE env)
  -G GEN              CMake generator (default: Ninja when ninja is installed, else Unix Makefiles)
  --triple TRIPLE     MinGW prefix (default: x86_64-w64-mingw32, or MINGW_TRIPLE env)
  --sysroot PATH      Force CMAKE_FIND_ROOT_PATH (default: from compiler or /usr/TRIPLE)
  --fresh             Remove build directory before configuring

Environment:
  MINGW_TRIPLE        Same as --triple
  CMAKE_GENERATOR     Default generator override (else: Ninja if installed, otherwise Unix Makefiles)
  BUILD_TYPE          Release / Debug / RelWithDebInfo / MinSizeRel

Examples:
  ./scripts/cross_build_windows.sh
  ./scripts/cross_build_windows.sh --server-only -j8
  ./scripts/cross_build_windows.sh --fresh -- -DWAVPACK=OFF
EOF
}

while [ $# -gt 0 ]; do
	case "$1" in
		-h|--help)
			usage
			exit 0
			;;
		--build-dir)
			BUILD_DIR="${2:?}"
			shift 2
			;;
		--release)
			BUILD_TYPE=Release
			shift
			;;
		--debug)
			BUILD_TYPE=Debug
			shift
			;;
		-j)
			JOBS="${2:?}"
			shift 2
			;;
		-G)
			GENERATOR="${2:?}"
			shift 2
			;;
		--server-only)
			SERVER_ONLY=1
			shift
			;;
		--triple)
			MINGW_TRIPLE="${2:?}"
			shift 2
			;;
		--sysroot)
			CUSTOM_SYSROOT="${2:?}"
			shift 2
			;;
		--fresh)
			FRESH=1
			shift
			;;
		--)
			shift
			while [ $# -gt 0 ]; do EXTRA_CMAKE+=("$1"); shift; done
			break
			;;
		*)
			die "Unknown option: $1 (use --help)"
			;;
	esac
done

if [ -z "${GENERATOR}" ]; then
	if command -v ninja >/dev/null 2>&1; then
		GENERATOR="Ninja"
	else
		GENERATOR="Unix Makefiles"
	fi
fi

pick_compiler() {
	local base="$1"
	if command -v "${base}-gcc-posix" >/dev/null 2>&1; then
		echo "${base}-gcc-posix"
	elif command -v "${base}-gcc" >/dev/null 2>&1; then
		echo "${base}-gcc"
	else
		return 1
	fi
}

CC_PROG="$(pick_compiler "${MINGW_TRIPLE}")" ||
	die "Missing MinGW GCC for prefix '${MINGW_TRIPLE}'. Install mingw-w64 (e.g. apt: mingw-w64 g++-mingw-w64)."

if [[ "${CC_PROG}" == *gcc-posix ]]; then
	CXX_PROG="${MINGW_TRIPLE}-g++-posix"
else
	CXX_PROG="${MINGW_TRIPLE}-g++"
fi

command -v "${CC_PROG}" >/dev/null 2>&1 || die "C compiler not found: ${CC_PROG}"
command -v "${CXX_PROG}" >/dev/null 2>&1 || die "C++ compiler not found: ${CXX_PROG}"

WINDRES="${MINGW_TRIPLE}-windres"
command -v "${WINDRES}" >/dev/null 2>&1 || die "windres not found: ${WINDRES}"

if [ -n "${CUSTOM_SYSROOT}" ]; then
	SYSROOT="${CUSTOM_SYSROOT}"
else
	SYSROOT="$("${CXX_PROG}" -print-sysroot 2>/dev/null || true)"
	if [ -z "${SYSROOT}" ] || [ "${SYSROOT}" = "/" ]; then
		SYSROOT="/usr/${MINGW_TRIPLE}"
	fi
fi

if [ ! -d "${SYSROOT}" ]; then
	echo >&2 "Warning: SYSROOT '${SYSROOT}' does not exist; CMake may still find libraries via compiler defaults."
fi

TOOLCHAIN_FILE="${BUILD_DIR}/Toolchain.cross-mingw.generated.cmake"
if [ "${FRESH}" -eq 1 ]; then
	rm -rf "${BUILD_DIR}"
fi
mkdir -p "${BUILD_DIR}"

cat > "${TOOLCHAIN_FILE}" <<EOF
# Generated by scripts/cross_build_windows.sh — do not hand-edit
set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(CMAKE_C_COMPILER ${CC_PROG})
set(CMAKE_CXX_COMPILER ${CXX_PROG})
set(CMAKE_RC_COMPILER ${WINDRES})

set(CMAKE_FIND_ROOT_PATH "${SYSROOT}")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY BOTH)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE BOTH)
EOF

CMAKE_ARGS=(
	"-S" "${PROJECT_ROOT}"
	"-B" "${BUILD_DIR}"
	"-DCMAKE_TOOLCHAIN_FILE=${TOOLCHAIN_FILE}"
	"-DCMAKE_BUILD_TYPE=${BUILD_TYPE}"
	"-DPREFER_BUNDLED_LIBS=ON"
)

CMAKE_ARGS+=("-G" "${GENERATOR}")

if [ "${SERVER_ONLY}" -eq 1 ]; then
	CMAKE_ARGS+=("-DCLIENT=OFF")
fi

CMAKE_ARGS+=("${EXTRA_CMAKE[@]}")

echo "==> Configure (Windows ${MINGW_TRIPLE}, ${BUILD_TYPE})"
echo "    CC=${CC_PROG} CXX=${CXX_PROG} SYSROOT=${SYSROOT}"
cmake "${CMAKE_ARGS[@]}"

echo "==> Build (${JOBS} jobs)"
cmake --build "${BUILD_DIR}" --parallel "${JOBS}"

echo "==> Done. Artifacts under: ${BUILD_DIR}"
if [ "${SERVER_ONLY}" -eq 0 ]; then
	ls -1 "${BUILD_DIR}/ninslash.exe" "${BUILD_DIR}/ninslash_srv.exe" 2>/dev/null || \
		ls -1 "${BUILD_DIR}/ninslash" "${BUILD_DIR}/ninslash_srv" 2>/dev/null || true
else
	ls -1 "${BUILD_DIR}/ninslash_srv.exe" 2>/dev/null || ls -1 "${BUILD_DIR}/ninslash_srv" 2>/dev/null || true
fi
