#!/usr/bin/env python3
"""Emit a byte-exact C++ array for a data file."""

import pathlib
import sys


def canonicalize_lua_bytes(data):
	"""Keep embedded Lua source byte-identical across checkout platforms."""
	return data.replace(b"\r\n", b"\n").replace(b"\r", b"\n")


def expand_inputs(arguments):
	result = []
	for argument in arguments:
		if not argument.startswith("@"):
			result.append((pathlib.Path(argument), None))
			continue
		manifest = pathlib.Path(argument[1:])
		for line in manifest.read_text(encoding="utf-8").splitlines():
			line = line.strip()
			if line and not line.startswith("#"):
				result.append((manifest.parent / line, line))
	return result


def main():
	arguments = sys.argv[1:]
	normalize_lf = False
	if arguments and arguments[0] == "--normalize-lf":
		normalize_lf = True
		arguments = arguments[1:]
	if len(arguments) < 2:
		raise SystemExit("usage: embed_binary.py [--normalize-lf] <input> [input ...] <symbol>")
	inputs = expand_inputs(arguments[:-1])
	chunks = []
	for path, label in inputs:
		data = path.read_bytes()
		if normalize_lf and path.suffix.lower() == ".lua":
			data = canonicalize_lua_bytes(data)
		if label is not None:
			chunks.append(b"-- source: " + label.encode("utf-8") + b"\n" + data)
		else:
			chunks.append(data)
	data = b"\n".join(chunks)
	symbol = arguments[-1]
	print("// Generated by scripts/embed_binary.py. Do not edit.")
	print("static const unsigned char %s[] = {" % symbol)
	for offset in range(0, len(data), 20):
		print("\t" + ",".join(str(byte) for byte in data[offset:offset + 20]) + ",")
	print("};")
	print("static const int %sSize = %d;" % (symbol, len(data)))


if __name__ == "__main__":
	main()
