#!/usr/bin/env python3
"""Emit a byte-exact C++ array for a data file."""

import pathlib
import sys


def expand_inputs(arguments):
	result = []
	for argument in arguments:
		if not argument.startswith("@"):
			result.append((pathlib.Path(argument), None))
			continue
		manifest = pathlib.Path(argument[1:])
		for line in manifest.read_text(encoding="utf-8").splitlines():
			line = line.strip()
			if line and not line.startswith("#"):
				result.append((manifest.parent / line, line))
	return result


def main():
	if len(sys.argv) < 3:
		raise SystemExit("usage: embed_binary.py <input> [input ...] <symbol>")
	inputs = expand_inputs(sys.argv[1:-1])
	chunks = []
	for path, label in inputs:
		if label is not None:
			chunks.append(b"-- source: " + label.encode("utf-8") + b"\n" + path.read_bytes())
		else:
			chunks.append(path.read_bytes())
	data = b"\n".join(chunks)
	symbol = sys.argv[-1]
	print("// Generated by scripts/embed_binary.py. Do not edit.")
	print("static const unsigned char %s[] = {" % symbol)
	for offset in range(0, len(data), 20):
		print("\t" + ",".join(str(byte) for byte in data[offset:offset + 20]) + ",")
	print("};")
	print("static const int %sSize = %d;" % (symbol, len(data)))


if __name__ == "__main__":
	main()
