#ifndef GAME_SHARED_PVE_PVE_ROGUELITE_H
#define GAME_SHARED_PVE_PVE_ROGUELITE_H

#include <base/system.h>

typedef unsigned long long uint64;

enum EPveMode
{
	PVE_MODE_ANY = 0,
	PVE_MODE_INVASION,
	PVE_MODE_HORDE,
	PVE_MODE_EXTRACTION,
};

enum
{
	PVE_HORDE_DEFENSE_RADIUS = 420,
};

enum EPveRarity
{
	PVE_RARITY_COMMON = 0,
	PVE_RARITY_RARE,
	PVE_RARITY_EPIC,
	PVE_RARITY_LEGENDARY,
};

enum EPveResearchTab
{
	PVE_TAB_CORE = 0,
	PVE_TAB_WEAPON,
	PVE_TAB_MODE,
};

enum EPveSpecialization
{
	PVE_SPECIALIZATION_NONE = 0,
	PVE_SPECIALIZATION_FIREARM,
	PVE_SPECIALIZATION_EXPLOSIVE,
	PVE_SPECIALIZATION_ELECTRIC,
	PVE_SPECIALIZATION_MELEE,
};

enum EPveKeyword
{
	PVE_KEYWORD_NONE = 0,
	PVE_KEYWORD_VULNERABLE = 1 << 0,
	PVE_KEYWORD_BARRIER = 1 << 1,
	PVE_KEYWORD_BLEED = 1 << 2,
	PVE_KEYWORD_FOCUS = 1 << 3,
	PVE_KEYWORD_BLAST_CHARGE = 1 << 4,
	PVE_KEYWORD_VOLTAGE = 1 << 5,
	PVE_KEYWORD_FURY = 1 << 6,
	PVE_KEYWORD_DRONE = 1 << 7,
};

enum EPveDroneModule
{
	PVE_DRONE_NONE = 0,
	PVE_DRONE_ASSAULT,
	PVE_DRONE_GUARDIAN,
	PVE_DRONE_REPAIR,
};

enum EPveCard
{
	// IDs 0-39 are save-game and protocol stable.
	PVE_CARD_COMBAT_TRAINING = 0,
	PVE_CARD_REINFORCED_PLATES,
	PVE_CARD_FIELD_SUPPLIES,
	PVE_CARD_SCAVENGER,
	PVE_CARD_AMMO_RESERVE,
	PVE_CARD_FIRST_AID,
	PVE_CARD_QUICK_HANDS,
	PVE_CARD_FINISHER,
	PVE_CARD_BOSS_HUNTER,
	PVE_CARD_KILL_CHAIN,
	PVE_CARD_GLASS_EDGE,
	PVE_CARD_DAMAGE_DAMPENER,
	PVE_CARD_EMERGENCY_PLATING,
	PVE_CARD_GUARDIAN,
	PVE_CARD_LAST_STAND,
	PVE_CARD_QUARTERMASTER,
	PVE_CARD_PREMIUM_STOCK,
	PVE_CARD_ENGINEER,
	PVE_CARD_RECYCLER,
	PVE_CARD_HOLLOW_POINT,
	PVE_CARD_SUSTAINED_FIRE,
	PVE_CARD_GUNSLINGER,
	PVE_CARD_DEMOLITION,
	PVE_CARD_WIDE_BLAST,
	PVE_CARD_CHAIN_REACTION,
	PVE_CARD_OVERCHARGE,
	PVE_CARD_ARC_CONDUCTOR,
	PVE_CARD_CAPACITOR,
	PVE_CARD_BERSERKER,
	PVE_CARD_BLOOD_DRIVE,
	PVE_CARD_SHOCKWAVE,
	PVE_CARD_DELVER,
	PVE_CARD_OBJECTIVE_SPECIALIST,
	PVE_CARD_ADAPTATION,
	PVE_CARD_BREATHING_ROOM,
	PVE_CARD_REAPER,
	PVE_CARD_SIEGE_MASTER,
	PVE_CARD_SABOTEUR,
	PVE_CARD_ESCAPE_ARTIST,
	PVE_CARD_NO_ONE_LEFT,

	// Twelve additional always-available base cards.
	PVE_CARD_MARKING_ROUNDS,
	PVE_CARD_BARRIER_CELL,
	PVE_CARD_SECOND_WIND,
	PVE_CARD_SALVAGE_INSTINCT,
	PVE_CARD_RESERVE_FUND,
	PVE_CARD_FIELD_RELAY,
	PVE_CARD_DRONE_CHASSIS,
	PVE_CARD_FOCUS_DRILL,
	PVE_CARD_BLAST_BATTERY,
	PVE_CARD_VOLTAGE_BANK,
	PVE_CARD_FURY_METER,
	PVE_CARD_OBJECTIVE_CACHE,

	// Core and drone research.
	PVE_CARD_PREDATOR,
	PVE_CARD_APEX_EXECUTION,
	PVE_CARD_BARRIER_REFIT,
	PVE_CARD_AEGIS_LOOP,
	PVE_CARD_LIQUID_ASSETS,
	PVE_CARD_WAR_ECONOMY,
	PVE_CARD_SERVO_LINK,
	PVE_CARD_ASSAULT_MODULE,
	PVE_CARD_GUARDIAN_MODULE,
	PVE_CARD_REPAIR_MODULE,
	PVE_CARD_COORDINATED_FIRMWARE,
	PVE_CARD_AUTONOMOUS_CORE,

	// Firearm research.
	PVE_CARD_CALIBRATION,
	PVE_CARD_PINPOINT_BURST,
	PVE_CARD_PERFECT_SEQUENCE,
	PVE_CARD_ARMOR_PIERCER,
	PVE_CARD_TACTICAL_RELOAD,
	PVE_CARD_CROSSFIRE,

	// Explosive research.
	PVE_CARD_PACKED_CHARGE,
	PVE_CARD_BREACH_CHARGE,
	PVE_CARD_CATACLYSM,
	PVE_CARD_SHRAPNEL,
	PVE_CARD_CONTROLLED_FUSE,
	PVE_CARD_SIEGE_PAYLOAD,

	// Electric research.
	PVE_CARD_CHARGE_COIL,
	PVE_CARD_CONDUCTIVE,
	PVE_CARD_THUNDERHEAD,
	PVE_CARD_FEEDBACK,
	PVE_CARD_STATIC_SHIELD,
	PVE_CARD_GRID_LINK,

	// Melee research.
	PVE_CARD_FURY_ENGINE,
	PVE_CARD_OPEN_WOUND,
	PVE_CARD_AVATAR_OF_WAR,
	PVE_CARD_GUARD_BREAKER,
	PVE_CARD_BLOOD_TEMPER,
	PVE_CARD_KINETIC_RETURN,

	// Mode research.
	PVE_CARD_CARTOGRAPHER,
	PVE_CARD_DEEP_SOVEREIGN,
	PVE_CARD_RELIC_SCANNER,
	PVE_CARD_FLOOR_MEMORY,
	PVE_CARD_WAVE_DIVIDEND,
	PVE_CARD_ENDLESS_ENGINE,
	PVE_CARD_FORTIFIED_CYCLE,
	PVE_CARD_HOLD_THE_LINE,
	PVE_CARD_COURIER,
	PVE_CARD_FINAL_DEPARTURE,
	PVE_CARD_SIGNAL_HACKER,
	PVE_CARD_CLEAN_EXIT,

	NUM_PVE_CARDS,

	PVE_SUPPLY_ARMOR = NUM_PVE_CARDS,
	PVE_SUPPLY_AMMO,
	PVE_SUPPLY_KITS,
	NUM_PVE_CHOICES,
};

enum EPveContract
{
	PVE_CONTRACT_GLASS_CANNON = 0,
	PVE_CONTRACT_ELITE_HUNT,
	PVE_CONTRACT_RESOURCE_DROUGHT,
	PVE_CONTRACT_SPEED_CLEAR,
	PVE_CONTRACT_FLAWLESS,
	PVE_CONTRACT_PURGE_PROTOCOL,
	PVE_CONTRACT_DOUBLE_WAVE,
	PVE_CONTRACT_BOSS_RUSH,
	PVE_CONTRACT_NO_RESPAWN,
	PVE_CONTRACT_TIGHT_DEADLINE,
	PVE_CONTRACT_BLACK_BOX,
	PVE_CONTRACT_OVERRUN,
	PVE_CONTRACT_ATTRITION,
	PVE_CONTRACT_OVERCLOCKED_HOSTILES,
	PVE_CONTRACT_SEALED_SUPPLIES,
	PVE_CONTRACT_ELITE_GUARD,
	PVE_CONTRACT_FORTIFICATION_TAX,
	PVE_CONTRACT_RISING_TIDE,
	PVE_CONTRACT_HEAVY_CARGO,
	PVE_CONTRACT_LOCKED_ROUTE,
	NUM_PVE_CONTRACTS,
};

enum
{
	NUM_PVE_BASE_CARDS = 19,
	NUM_PVE_RESEARCH_CARDS = NUM_PVE_CARDS - NUM_PVE_BASE_CARDS,
};

enum EPveContractState
{
	PVE_CONTRACT_STATE_NONE = 0,
	PVE_CONTRACT_STATE_ACTIVE,
	PVE_CONTRACT_STATE_SUCCESS,
	PVE_CONTRACT_STATE_FAILED,
};

enum EPveIntermissionState
{
	PVE_INTERMISSION_NONE = 0,
	PVE_INTERMISSION_CONTRACT,
	PVE_INTERMISSION_PERK,
};

enum EPveDroneState
{
	PVE_DRONE_STATE_DEPLOYING = 0,
	PVE_DRONE_STATE_FOLLOWING,
	PVE_DRONE_STATE_ACTING,
	PVE_DRONE_STATE_DISABLED,
	PVE_DRONE_STATE_DESTROYED,
	PVE_DRONE_STATE_REBUILDING,
	PVE_DRONE_STATE_SWITCHING,
};

enum EPveRewardReason
{
	PVE_REWARD_INVASION_DEPTH = 0,
	PVE_REWARD_HORDE_SECTION,
	PVE_REWARD_EXTRACTION,
	PVE_REWARD_CONTRACT,
};

enum EPveValidationError
{
	PVE_VALIDATION_EXPIRED = 1,
	PVE_VALIDATION_DUPLICATE,
	PVE_VALIDATION_RANGE,
	PVE_VALIDATION_NOT_OFFERED,
	PVE_VALIDATION_PROGRESS,
	PVE_VALIDATION_MODULE_LOCKED,
	PVE_VALIDATION_MODULE_COOLDOWN,
};

enum EPveInvasionRetryChoice
{
	PVE_INVASION_RETRY = 0,
	PVE_INVASION_RESET,
};

enum EPveInvasionRetryResult
{
	PVE_INVASION_RETRY_RESULT_RETRY = 0,
	PVE_INVASION_RETRY_RESULT_RESET,
	PVE_INVASION_RETRY_RESULT_FINAL_FAILURE,
};

struct CPveCardDef
{
	int m_ID;
	const char *m_pName;
	const char *m_pDescription;
	int m_Rarity;
	int m_MaxStacks;
	int m_ResearchCost;
	bool m_Base;
	bool m_Legendary;
	unsigned m_Keywords;
	int m_aPrerequisites[3];
	int m_NumPrerequisites;
	int m_Tab;
	int m_Branch;
	int m_Tier;
	int m_Mode;
	int m_Specialization;
};

struct CPveContractDef
{
	int m_ID;
	const char *m_pName;
	const char *m_pRule;
	const char *m_pRisk;
	int m_Mode;
};

// Version 2 uses 100 stable card bits. Keeping the words explicit makes the
// network representation portable and leaves 28 reserved high bits.
struct CPveResearchMask
{
	uint64 m_aWords[2];

	CPveResearchMask(unsigned long long Low = 0, unsigned long long High = 0);
	bool Test(int CardID) const;
	void Set(int CardID, bool Value = true);
	void Sanitize();
	bool PrerequisitesMet(int CardID) const;
	bool operator==(const CPveResearchMask &Other) const;
	bool operator!=(const CPveResearchMask &Other) const { return !(*this == Other); }
};

const CPveCardDef *PveCardDef(int ID);
const CPveContractDef *PveContractDef(int ID);
const char *PveChoiceName(int ID);
const char *PveChoiceDescription(int ID);
const char *PveRarityName(int Rarity);
const char *PveRewardReasonName(int Reason);

bool PveCardIsBase(int ID);
bool PveCardIsUnlocked(int ID, const CPveResearchMask &ResearchMask);
bool PveResearchMaskIsValid(const CPveResearchMask &ResearchMask);
CPveResearchMask PveSanitizeResearchMask(CPveResearchMask ResearchMask);
bool PveContractAvailableInMode(int ContractID, int Mode);
bool PveValidateDefinitions(char *pError, int ErrorSize);

#endif
